version: "3"
services:

  frontend:
    image: plone/plone-frontend:14.0.0-alpha-node14
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/Plone
    restart: always
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:6.0.0a1-python39
    environment:
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    restart: always
    ports:
    - "8080:8080"
    volumes:
      - data:/data        

volumes:
  data: {}
