- hosts: "all"
  gather_facts: True
  become: yes

  tasks:
  - name: Install Packages
    ansible.builtin.apt:
      name:
        - nginx
        - docker.io
        - python3-pip
      state: present
      update_cache: yes

  - name: Install Docker Python Packages
    ansible.builtin.pip:
      name:
        - docker
        - docker-compose
      state: present

  - name: Create user plone
    ansible.builtin.user:
      name: plone
      comment: Plone User
      groups:
        - docker
      shell: '/bin/bash'
      remove: yes
      append: yes
      state: present

  - name: Set SSH Key for plone
    ansible.builtin.authorized_key:
      user: plone
      key: "{{ item }}"
      state: present
    with_items:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJIwjHxRAM1a8zc1kuTJ0GyzvloaBTz/fO7bGoNOlxY2lnUDop+q3CbHF28IkmVQCk28I+MXCnUXG6ARZgnBcb4LDey9WPVsiy3NRCXOmaZK6NKmKUejdA5Y4ZTHbs6rdIInDLWaFxzoxg5p/LaXUaTrKra2SpGc3kv7xKiZKXyTznFjFSv/u6Wm/vvZopWM6m4k8Z00fTUtxQO0eWKArStF99YFszUDU2w2jhL7n8irLow0UqjNjp0MvkPiic2SueoylQRIlD57XzveMBpGynYdsZWKDa3Czzo5ykHPLYrOByioKKjnpwgruXnXkkN4ov8sK+LqqAXaicxed6ohbOh68IWVB8nssb+RbISmzzpIXUwd1qkAyeiSjt5b9MFcIT56zeRb5B+aWZbYffc+pKy8kAjrYHCWEFl6O3N+M/bI9jgtXcZ9L6FSBN5vWjgRQPn7UwiMXIUssm0lU5AgCxs7q7S0xACj0xVFk5NeUM9vcCzXkY9vAjJmE1hzBWeOVhhQqLKmkbi/scr5hW2rrNwnuPBpyHUu2wTIyGHbnZ9CCwU3u21XDyvvO9ufxDjIH3v2EwEPqpbejKRM8QUH6YuH2goy89yQQijsC0YUE8AlJpbs9ctxSyzsJ6Z3ZwHJA681Ei15omhab2iwmT4KcS+3mC5pSCsFQgA4OsJKy5OQ== ericof@gmail.com"

  - name: Create Project directory
    ansible.builtin.file:
      dest: /home/plone/project/
      state: directory
      owner: plone
      group: plone
      mode: 0750

  - name: Copy configuration
    ansible.builtin.copy:
      src: ./docker-compose.yml
      dest: /home/plone/project/docker-compose.yml
      owner: plone
      group: plone
      mode: 0640

  - name: Copy configuration
    ansible.builtin.copy:
      src: files/nginx/default
      dest: /etc/nginx/sites-enabled/default
      mode: '0644'

  - name: restart nginx
    service:
      name: nginx
      state: reloaded